#Requires AutoHotkey v2.0
#SingleInstance Force
; ============================================================
;  Open Public User Folder   (workflow, saved 2026-07-07)
;  Trigger by voice:  "open Open Public User Folder"
;
;  Generated by Workflow Studio — don't edit steps here.
;  Edit by voice:  "open workflow studio"  ->  pick "Open Public User Folder"
;  Steps live in:  workflows\OpenPublicUserFolder.steps.txt
; ============================================================
#Include "%A_ScriptDir%\..\lib\_Common.ahk"
#Include "%A_ScriptDir%\..\lib\Workflow.ahk"
RunWorkflow(A_ScriptDir "\..\workflows\OpenPublicUserFolder.steps.txt")
